spring:
  application:
    name: hgp-test
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:test
    platform: h2
    #    url: jdbc:mysql://localhost:3306/gghqfw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1830000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database: mysql
    database: h2
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  h2:
    console:
      path: /h2-console
      enabled: true
# spring.h2.console.settings.web-allow-others=true //设置为true，h2 web consloe就可以在远程访问了。否则只能在本机访问。
# spring.h2.console.enabled=true                   //设置为true，程序开启时就会启动h2 web console(默认是false) 访问URL是 http://localhost:8080/h2-console

info:
  app:
    name: ${spring.application.name}
    version: V0.7.1.2
    time: 2018年10月17日 12:00:00
  describe: 项目描述
  home: /
  author: administrator
  licensed: MIT Licensed

server:
  port: 8088
  servlet:
    context-path: /test-test
# http://localhost:8088/test-test/example001/index.html
# http://localhost:8088/test-test/example001/login.html
# http://localhost:8088/test-test/projects/layuimini/v1.0.4/login.html
# http://localhost:8088/test-test/projects/layuimini/v2.0.3/login.html
# http://localhost:8088/test-test/projects/layuimini/v2.0.3/login.html
# http://localhost:8088/test-test/pages/back-end/login/login.html

#  freemarker静态资源配置
spring.freemarker.template-loader-path: classpath:/templates
spring.freemarker.cache: false
spring.freemarker.charset: UTF-8
spring.freemarker.check-template-location: true
spring.freemarker.content-type: text/html
spring.freemarker.expose-request-attributes: true
spring.freemarker.expose-session-attributes: true
spring.freemarker.expose-spring-macro-helpers: true
spring.freemarker.request-context-attribute: request
spring.freemarker.settings.template_update_delay: 0
spring.freemarker.suffix: .ftl

#spring.mvc.view.prefix: /pages/
spring.mvc.view.suffix: .ftl

#server.compression.enabled: true
#server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
# 默认就是2048 byte
#server.compression.min-response-size: 2048

#logging.level.root: WARN
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: ERROR


spring.redis:
  database: 0
  host: localhost
  port: 6379
  password:
  timeout: 5000ms

eureka:
  instance:
#    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 3
#    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.4.151:8761/eureka

logging:
  level:
    org.hibernate: info
